apiVersion: v1
kind: PersistentVolume
metadata:
  #namespace: monitoring # namespace verince prometheus kurulumunda hata olusuyor. The Deployment "grafana" is invalid: spec.template.spec.containers[0].volumeMounts[1].name: Not found: "grafana-storage"
  name: grafana-storage
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef: # bunu yalnızca grafana kullansin diye ayiriyoruz. cunlu local storage dynamic provisioning desteklenmiyor.
    name: grafana-storage
    #namespace: monitoring
  local:
    path: /tmp #/mnt/disks/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname # shard in -0 -1 diye de kullanabiliriz.
          operator: In
          values:
          - node1
          - node2
          - node3