apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /tmp #/mnt/disks/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname # shard in -0 -1 diye de kullanabiliriz.
          operator: In
          values:
          - node1
          - node2
          - node3